server:
  port: 8080

application:
  api-prefix: /serviziosanitario

spring:
  application:
    name: GATEWAY-SERVICE
  redis: 
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    password: ${SPRING_REDIS_PASSWORD}
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: shareyourpassion_local
      save-mode: on-set-attribute
      
  cloud:
    gateway:
      routes:
        # PRIMA LE SPECIFICHE
        - id: landing-service-route
          uri: lb://LANDING-SERVICE
          predicates:
            - Path=${application.api-prefix}/landing/**
            
        - id: cartella-service-route
          uri: lb://CARTELLA-SERVICE
          predicates:
            - Path=${application.api-prefix}/cartella/**

        # POI QUELLA GENERICA (Catch-all)
        - id: registration-login-route
          uri: lb://IDENTIFICAZIONE-SERVICE
          predicates:
            - Path=${application.api-prefix}/**
          filters:
            - GenerateJwtOnLogin



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  level:
    root: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.resource.transaction: INFO
    org.springframework.data.jpa.repository.query: INFO
    org.springframework.orm.jpa: INFO

# --- Configurazione Sicurezza Personalizzata ---
security:
  preliminary-filter:
    enabled: true
    allowed-urls: ${PUBLIC_ENDPOINTS}
    required-headers: Serviziosanitario,Authorities,x-svz-header
 
app:
  security:
    public-endpoints: ${PUBLIC_ENDPOINTS}
    cors:  
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: ${CORS_ALLOWED_METHODS} 
      allowed-headers: ${CORS_ALLOWED_HEADERS}
      exposed-headers: ${CORS_ALLOWED_EXPOSED_HEADERS}
      max-age: ${CORS_ALLOWED_MAX_AGE}
      require-https: ${CORS_ALLOWED_REQUIRE_HTTPS} 
    jwt:
      secret: ${JWT_SECRET_KEY}
      expiration-ms: ${JWT_EXPIRATION_MS}
      prefix: ${PREFIX}
      issuer: ${ISSUER}
  
