server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: login-route
          uri: lb://IDENTIFICAZIONE-SERVICE
          predicates:
            - Path=/serviziosanitario/**
           # - Method=POST
           # - Header=Authorization, Basic .+
           # - Header=X-SVZ-HEADER
          #filters:
           #  - RewritePath=/serviziosanitario/login, /api/v1/serviziosanitario/login

        - id: register-route
          uri: lb://IDENTIFICAZIONE-SERVICE
          predicates:
            - Path=/auth/register
            - Method=POST
            - Header=X-SYP-HEADER
          filters:
            - RewritePath=/auth/register, /api/v1/auth/register
 # --- ROTTA GENERICA PER TUTTE LE ALTRE API (protette da JWT) ---
        - id: api-catch-all-route
          # Questo uri è solo un placeholder, il routing vero avviene a valle
          # Ma è più comune avere rotte specifiche per servizio come avevi prima
          uri: lb://dummy-service 
          predicates:
            # Cattura tutte le altre richieste sotto /api/
            - Path=/api/**
          # Questa rotta non fa nulla da sola, serve solo a raggruppare
          # le richieste che dovranno passare dal filtro JWT.
          # Le tue rotte specifiche per 'identificazione' e 'cartella' sono migliori.
          # Le lascio qui sotto come esempio corretto.
        # --- Le tue rotte specifiche per i servizi protetti ---
        - id: identificazione-service-route
          uri: lb://IDENTIFICAZIONE-SERVICE
          predicates:
            - Path=/api/v1/identificazione/**

        - id: cartella-service-route
          uri: lb://CARTELLA-SERVICE
          predicates:
            - Path=/api/v1/cartella/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  level:
    root: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.resource.transaction: INFO
    org.springframework.data.jpa.repository.query: INFO
    org.springframework.orm.jpa: INFO

# --- Configurazione Sicurezza Personalizzata ---
security:
  preliminary-filter:
    enabled: true
    allowed-urls: [ "/error", "/serviziosanitario/registration","/serviziosanitario/login" ]
    required-headers: ServizioSanitario,Authorities
 
app:
  security:
    public-endpoints: ${PUBLIC_ENDPOINTS}
    cors:  
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: ${CORS_ALLOWED_METHODS} 
      allowed-headers: ${CORS_ALLOWED_HEADERS}
      exposed-headers: ${CORS_ALLOWED_EXPOSED_HEADERS}
      max-age: ${CORS_ALLOWED_MAX_AGE}
      require-https: ${CORS_ALLOWED_REQUIRE_HTTPS} 
    jwt:
      secret: ${JWT_SECRET_KEY}
      expiration-ms: ${JWT_EXPIRATION_MS}
      prefix: ${PREFIX}
  datasource:
    url: jdbc:mysql://localhost:3306/${DATASOURCE_GATEWAY_DATABASE}
    username: ${DATASOURCE_GATEWAY_USERNAME}
    password: ${DATASOURCE_GATEWAY_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Hikari-Gateway # Diamo un nome al pool, utile per i log
      maximum-pool-size: 10 # Dimensione massima. Un buon punto di partenza. Non esagerare!
      minimum-idle: 5       # Connessioni minime da tenere sempre pronte
      connection-timeout: 30000 # 30 secondi per ottenere una connessione prima di un errore
      idle-timeout: 600000      # 10 minuti prima di chiudere una connessione inattiva
      max-lifetime: 1800000     # 30 minuti di vita massima per una connessione  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

