server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: login-route
          uri: lb://IDENTIFICAZIONE-SERVICE
          predicates:
            - Path=/serviziosanitario/**
           # - Method=POST
           # - Header=Authorization, Basic .+
           # - Header=X-SVZ-HEADER
          #filters:
           #  - RewritePath=/serviziosanitario/login, /api/v1/serviziosanitario/login

        - id: register-route
          uri: lb://IDENTIFICAZIONE-SERVICE
          predicates:
            - Path=/auth/register
            - Method=POST
            - Header=X-SYP-HEADER
          filters:
            - RewritePath=/auth/register, /api/v1/auth/register
 # --- ROTTA GENERICA PER TUTTE LE ALTRE API (protette da JWT) ---
        - id: api-catch-all-route
          # Questo uri è solo un placeholder, il routing vero avviene a valle
          # Ma è più comune avere rotte specifiche per servizio come avevi prima
          uri: lb://dummy-service 
          predicates:
            # Cattura tutte le altre richieste sotto /api/
            - Path=/api/**
          # Questa rotta non fa nulla da sola, serve solo a raggruppare
          # le richieste che dovranno passare dal filtro JWT.
          # Le tue rotte specifiche per 'identificazione' e 'cartella' sono migliori.
          # Le lascio qui sotto come esempio corretto.
        # --- Le tue rotte specifiche per i servizi protetti ---
        - id: identificazione-service-route
          uri: lb://IDENTIFICAZIONE-SERVICE
          predicates:
            - Path=/api/v1/identificazione/**

        - id: cartella-service-route
          uri: lb://CARTELLA-SERVICE
          predicates:
            - Path=/api/v1/cartella/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  level:
    root: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.resource.transaction: INFO
    org.springframework.data.jpa.repository.query: INFO
    org.springframework.orm.jpa: INFO

# --- Configurazione Sicurezza Personalizzata ---
security:
  preliminary-filter:
    enabled: true
    allowed-urls: [ "/error", "/serviziosanitario/registration","/serviziosanitario/login" ]
    required-headers: ServizioSanitario,Authorities

  # --- Configurazione JWT ---
jwt:
    # Il segreto ora viene letto dal file .env per non committealo
  secret: ${JWT_SECRET_KEY}
  expiration-ms: 3600000 # 1 ora, comodo per il debug locale
  prefix: "Bearer "

  # --- Configurazione CORS (permissiva per lo sviluppo locale) ---
  cors:
    allowed-origins: [ "http://localhost:4200", "http://localhost:8080" ]
    allowed-methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    allowed-headers: [ "*" ]
    exposed-headers: [ "Authorization", "Content-Type" ]
    max-age: 3600
    require-https: false


app:
  security:
    public-endpoints:
      - "/serviziosanitario/login"
      - "/serviziosanitario/registration"
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
      - "/webjars/swagger-ui/**"
      - "/error"
    allowed-origins: [ "http://localhost:4200", "http://localhost:8080" ]
    allowed-methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
    allowed-headers: [ "*" ]
    exposed-headers: [ "Authorization", "Content-Type" ]
    max-age: 3600
    require-https: false
