server:
  port: 0

spring:
  # --- Configurazione del Database ---
  datasource:
    url: jdbc:mysql://localhost:3306/identificazione_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # --- Configurazione di JPA/Hibernate ---
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

# --- Configurazione del client Eureka ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: DEBUG